services:
  main:
    image: intersectional-fairness
    build: .
    volumes:
      - type: bind
        source: ${FOLDER:-results}
        target: /project/results
        bind:
          create_host_path: true

  baselines:
    image: intersectional-fairness
    depends_on: [ main ]
    command: python baselines.py --folder results
    volumes:
      - type: bind
        source: ${FOLDER:-results}
        target: /project/results

  clear:
    image: intersectional-fairness
    depends_on: [ main ]
    command: python clear.py --folder results
    volumes:
      - type: bind
        source: ${FOLDER:-results}
        target: /project/results

  gedi:
    image: intersectional-fairness
    depends_on: [ main ]
    command: python gedi.py --folder results
    volumes:
      - type: bind
        source: ${FOLDER:-results}
        target: /project/results
